name: ifs_parts_flutter
description: IFS Parts desktop/tablet app (Flutter)
publish_to: "none"

environment:
  sdk: ">=3.9.0 <4.0.0"

version: 0.1.0+1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  path_provider: ^2.1.3
  file_selector: ^1.0.3
  printing: ^5.13.4
  window_size: 0.1.0
  pdf: 3.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/questions.json
